/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_package;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base_left_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Close_panel = new javax.swing.JPanel();
        Close_icon_lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);

        Base_left_panel.setBackground(new java.awt.Color(252, 45, 255));

        javax.swing.GroupLayout Base_left_panelLayout = new javax.swing.GroupLayout(Base_left_panel);
        Base_left_panel.setLayout(Base_left_panelLayout);
        Base_left_panelLayout.setHorizontalGroup(
            Base_left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        Base_left_panelLayout.setVerticalGroup(
            Base_left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(252, 45, 255));

        Close_panel.setBackground(new java.awt.Color(252, 45, 255));
        Close_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Close_icon_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_4.png"))); // NOI18N
        Close_icon_lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout Close_panelLayout = new javax.swing.GroupLayout(Close_panel);
        Close_panel.setLayout(Close_panelLayout);
        Close_panelLayout.setHorizontalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_icon_lable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        Close_panelLayout.setVerticalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_icon_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 847, Short.MAX_VALUE)
                .addComponent(Close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base_left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_icon_lableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseEntered
        // TODO add your handling code here:
        Close_panel.setBackground(new java.awt.Color(249, 9, 9));
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_2.png")));
    }//GEN-LAST:event_Close_icon_lableMouseEntered

    private void Close_icon_lableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseExited
        try {
            // TODO add your handling code here:
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(Base.class.getName()).log(Level.SEVERE, null, ex);
        }
        Close_panel.setBackground(new java.awt.Color(252, 45, 255));
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_4.png")));
    }//GEN-LAST:event_Close_icon_lableMouseExited

    private void Close_icon_lableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Close_icon_lableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base_left_panel;
    private javax.swing.JLabel Close_icon_lable;
    private javax.swing.JPanel Close_panel;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
