/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_package;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankit
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Base_left_panel = new javax.swing.JPanel();
        Side_left_panel_1 = new javax.swing.JPanel();
        Side_left_lable_1 = new javax.swing.JLabel();
        Side_left_panel_2 = new javax.swing.JPanel();
        Side_left_lable_2 = new javax.swing.JLabel();
        Side_left_panel_3 = new javax.swing.JPanel();
        Side_left_lable_3 = new javax.swing.JLabel();
        Side_left_panel_4 = new javax.swing.JPanel();
        Side_left_lable_4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Close_panel = new javax.swing.JPanel();
        Close_icon_lable = new javax.swing.JLabel();
        button1 = new java.awt.Button();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);

        Base_left_panel.setBackground(new java.awt.Color(252, 45, 255));

        Side_left_panel_1.setBackground(new java.awt.Color(252, 45, 255));
        Side_left_panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Side_left_panel_1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Side_left_panel_1MouseEntered(evt);
            }
        });

        Side_left_lable_1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Side_left_lable_1.setForeground(new java.awt.Color(255, 255, 255));
        Side_left_lable_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Side_left_lable_1.setText("Home");

        javax.swing.GroupLayout Side_left_panel_1Layout = new javax.swing.GroupLayout(Side_left_panel_1);
        Side_left_panel_1.setLayout(Side_left_panel_1Layout);
        Side_left_panel_1Layout.setHorizontalGroup(
            Side_left_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Side_left_panel_1Layout.setVerticalGroup(
            Side_left_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        Side_left_panel_2.setBackground(new java.awt.Color(252, 45, 255));
        Side_left_panel_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Side_left_panel_2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Side_left_panel_2MouseEntered(evt);
            }
        });

        Side_left_lable_2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Side_left_lable_2.setForeground(new java.awt.Color(255, 255, 255));
        Side_left_lable_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Side_left_lable_2.setText("Friends");

        javax.swing.GroupLayout Side_left_panel_2Layout = new javax.swing.GroupLayout(Side_left_panel_2);
        Side_left_panel_2.setLayout(Side_left_panel_2Layout);
        Side_left_panel_2Layout.setHorizontalGroup(
            Side_left_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Side_left_panel_2Layout.setVerticalGroup(
            Side_left_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        Side_left_panel_3.setBackground(new java.awt.Color(252, 45, 255));
        Side_left_panel_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Side_left_panel_3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Side_left_panel_3MouseEntered(evt);
            }
        });

        Side_left_lable_3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Side_left_lable_3.setForeground(new java.awt.Color(255, 255, 255));
        Side_left_lable_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Side_left_lable_3.setText("Massage");

        javax.swing.GroupLayout Side_left_panel_3Layout = new javax.swing.GroupLayout(Side_left_panel_3);
        Side_left_panel_3.setLayout(Side_left_panel_3Layout);
        Side_left_panel_3Layout.setHorizontalGroup(
            Side_left_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );
        Side_left_panel_3Layout.setVerticalGroup(
            Side_left_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        Side_left_panel_4.setBackground(new java.awt.Color(252, 45, 255));
        Side_left_panel_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Side_left_panel_4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Side_left_panel_4MouseEntered(evt);
            }
        });

        Side_left_lable_4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Side_left_lable_4.setForeground(new java.awt.Color(255, 255, 255));
        Side_left_lable_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Side_left_lable_4.setText("Profile");

        javax.swing.GroupLayout Side_left_panel_4Layout = new javax.swing.GroupLayout(Side_left_panel_4);
        Side_left_panel_4.setLayout(Side_left_panel_4Layout);
        Side_left_panel_4Layout.setHorizontalGroup(
            Side_left_panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Side_left_panel_4Layout.setVerticalGroup(
            Side_left_panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_left_lable_4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Base_left_panelLayout = new javax.swing.GroupLayout(Base_left_panel);
        Base_left_panel.setLayout(Base_left_panelLayout);
        Base_left_panelLayout.setHorizontalGroup(
            Base_left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_left_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Base_left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Side_left_panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Side_left_panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Side_left_panel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Side_left_panel_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Base_left_panelLayout.setVerticalGroup(
            Base_left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_left_panelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(Side_left_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Side_left_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Side_left_panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Side_left_panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(252, 45, 255));

        Close_panel.setBackground(new java.awt.Color(252, 45, 255));
        Close_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Close_icon_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_4.png"))); // NOI18N
        Close_icon_lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_icon_lableMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout Close_panelLayout = new javax.swing.GroupLayout(Close_panel);
        Close_panel.setLayout(Close_panelLayout);
        Close_panelLayout.setHorizontalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_icon_lable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        Close_panelLayout.setVerticalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_icon_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 910, Short.MAX_VALUE)
                .addComponent(Close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        button1.setLabel("button1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base_left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1231, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_icon_lableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseEntered
        // TODO add your handling code here:
        Close_panel.setBackground(new java.awt.Color(249, 9, 9));
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_2.png")));
    }//GEN-LAST:event_Close_icon_lableMouseEntered

    private void Close_icon_lableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseExited
        try {
            // TODO add your handling code here:
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(Base.class.getName()).log(Level.SEVERE, null, ex);
        }
        Close_panel.setBackground(new java.awt.Color(252, 45, 255));
        Close_icon_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/icon/icons8_shutdown_30px_4.png")));
    }//GEN-LAST:event_Close_icon_lableMouseExited

    private void Close_icon_lableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_icon_lableMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Close_icon_lableMouseClicked

    private void Side_left_panel_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_1MouseEntered
        // TODO add your handling code here:
        Side_left_panel_1.setBackground(new java.awt.Color(204, 0, 204));
    }//GEN-LAST:event_Side_left_panel_1MouseEntered

    private void Side_left_panel_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_1MouseExited
        // TODO add your handling code here:
        Side_left_panel_1.setBackground(new java.awt.Color(252, 45, 255));
    }//GEN-LAST:event_Side_left_panel_1MouseExited

    private void Side_left_panel_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_2MouseEntered
        // TODO add your handling code here:
        Side_left_panel_2.setBackground(new java.awt.Color(204, 0, 204));
    }//GEN-LAST:event_Side_left_panel_2MouseEntered

    private void Side_left_panel_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_2MouseExited
        // TODO add your handling code here:
        Side_left_panel_2.setBackground(new java.awt.Color(252, 45, 255));
    }//GEN-LAST:event_Side_left_panel_2MouseExited

    private void Side_left_panel_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_3MouseEntered
        // TODO add your handling code here:
        Side_left_panel_3.setBackground(new java.awt.Color(204, 0, 204));
    }//GEN-LAST:event_Side_left_panel_3MouseEntered

    private void Side_left_panel_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_3MouseExited
        // TODO add your handling code here:
        Side_left_panel_3.setBackground(new java.awt.Color(252, 45, 255));
    }//GEN-LAST:event_Side_left_panel_3MouseExited

    private void Side_left_panel_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_4MouseEntered
        // TODO add your handling code here:
        Side_left_panel_4.setBackground(new java.awt.Color(204, 0, 204));
    }//GEN-LAST:event_Side_left_panel_4MouseEntered

    private void Side_left_panel_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_left_panel_4MouseExited
        // TODO add your handling code here:
        Side_left_panel_4.setBackground(new java.awt.Color(252, 45, 255));
    }//GEN-LAST:event_Side_left_panel_4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base_left_panel;
    private javax.swing.JLabel Close_icon_lable;
    private javax.swing.JPanel Close_panel;
    private javax.swing.JLabel Side_left_lable_1;
    private javax.swing.JLabel Side_left_lable_2;
    private javax.swing.JLabel Side_left_lable_3;
    private javax.swing.JLabel Side_left_lable_4;
    private javax.swing.JPanel Side_left_panel_1;
    private javax.swing.JPanel Side_left_panel_2;
    private javax.swing.JPanel Side_left_panel_3;
    private javax.swing.JPanel Side_left_panel_4;
    private java.awt.Button button1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
